# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    context:
      codecov
    docker:
      - image: circleci/golang:1.9
      - image: redis:5.0.3
      
    working_directory: /go/src/github.com/rerost/redblocks-go
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
